In [1]:
import pandas as pd
import numpy as np
import os
import requests
from io import StringIO
import json

from table_services import inject_tables
from metadata_services import build_metadata

In [2]:
url = "https://docs.google.com/spreadsheets/d/1UD76pvPEv7q4Fe0o83V3vulwzboGg3fm06YtbMYaUFQ/export?format=csv&gid=903602598"

response = requests.get(url)

if response.status_code != 200:
    raise Exception("Gagal akses spreadsheet. Cek permission / gid.")

csv_data = StringIO(response.text)

In [3]:
df = pd.read_csv(csv_data, encoding='utf-8')
df.head()

,kodeKecamatan,namaKecamatan,namaKec_Kapital,nomorVolume,nomorKatalog,nomorPublikasi,jumlahHalaman,sumberIlustrasi,namaPenyunting,namaPenulis,namaLayouter,namaInfografis,namaPenerjemah
0,6105160,Balai,BALAI,15,1102001.611,61050.24012,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John"
1,6105190,Beduai,BEDUAI,15,1102001.611,61050.24013,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John"
2,6105130,Bonti,BONTI,15,1102001.611,61050.24014,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John"
3,6105220,Entikong,ENTIKONG,15,1102001.611,61050.24015,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John"
4,6105120,Jangkang,JANGKANG,15,1102001.611,61050.24016,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John"

In [4]:
df["namaPenyunting_joint"] = df["namaPenyunting"].str.replace(", ", " • ")
df["namaPenulis_joint"] = df["namaPenulis"].str.replace(", ", " • ")
df["namaLayouter_joint"] = df["namaLayouter"].str.replace(", ", " • ")
df["namaInfografis_joint"] = df["namaInfografis"].str.replace(", ", " • ")
df["namaPenerjemah_joint"] = df["namaPenerjemah"].str.replace(", ", " • ")

In [5]:
df.head()

,kodeKecamatan,namaKecamatan,namaKec_Kapital,nomorVolume,nomorKatalog,nomorPublikasi,jumlahHalaman,sumberIlustrasi,namaPenyunting,namaPenulis,namaLayouter,namaInfografis,namaPenerjemah,namaPenyunting_joint,namaPenulis_joint,namaLayouter_joint,namaInfografis_joint,namaPenerjemah_joint
0,6105160,Balai,BALAI,15,1102001.611,61050.24012,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John",Yudistira Elton John • Riofebri Prasetya,Riofebri Prasetya • Muhammad Andi Williansyah,Muhammad Andi Williansyah • Bertolomeus Laksan...,Bertolomeus Laksana Jayadri • Rio Febri Prasetya,Muhammad Andi Williansyah • Yudistira Elton John
1,6105190,Beduai,BEDUAI,15,1102001.611,61050.24013,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John",Yudistira Elton John • Riofebri Prasetya,Riofebri Prasetya • Muhammad Andi Williansyah,Muhammad Andi Williansyah • Bertolomeus Laksan...,Bertolomeus Laksana Jayadri • Rio Febri Prasetya,Muhammad Andi Williansyah • Yudistira Elton John
2,6105130,Bonti,BONTI,15,1102001.611,61050.24014,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John",Yudistira Elton John • Riofebri Prasetya,Riofebri Prasetya • Muhammad Andi Williansyah,Muhammad Andi Williansyah • Bertolomeus Laksan...,Bertolomeus Laksana Jayadri • Rio Febri Prasetya,Muhammad Andi Williansyah • Yudistira Elton John
3,6105220,Entikong,ENTIKONG,15,1102001.611,61050.24015,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John",Yudistira Elton John • Riofebri Prasetya,Riofebri Prasetya • Muhammad Andi Williansyah,Muhammad Andi Williansyah • Bertolomeus Laksan...,Bertolomeus Laksana Jayadri • Rio Febri Prasetya,Muhammad Andi Williansyah • Yudistira Elton John
4,6105120,Jangkang,JANGKANG,15,1102001.611,61050.24016,xxx+123 hal/pages,BPS Kabupaten Sanggau,"Yudistira Elton John, Riofebri Prasetya","Riofebri Prasetya, Muhammad Andi Williansyah","Muhammad Andi Williansyah, Bertolomeus Laksana...","Bertolomeus Laksana Jayadri, Rio Febri Prasetya","Muhammad Andi Williansyah, Yudistira Elton John",Yudistira Elton John • Riofebri Prasetya,Riofebri Prasetya • Muhammad Andi Williansyah,Muhammad Andi Williansyah • Bertolomeus Laksan...,Bertolomeus Laksana Jayadri • Rio Febri Prasetya,Muhammad Andi Williansyah • Yudistira Elton John

In [6]:
url = "https://docs.google.com/spreadsheets/d/14br7OEiGZJKN_NBUKmDpnWO2P9CsXlruk__m1O29brg/export?format=csv&gid=583286261"

response = requests.get(url)

if response.status_code != 200:
    raise Exception("Gagal akses spreadsheet. Cek permission / gid.")

csv_data = StringIO(response.text)

In [7]:
data_kcda2026 = pd.read_csv(csv_data, encoding='utf-8')
data_kcda2026.head()

,kodeDesa,volume,kodeKecamatan,katalog,noPublikasi,namaKecamatan,statusDesKel,namaDesa,alokasiDanaDesa,danaDesa,...,r1001c1String,r1001b1String,r403c2String,proyeksiPendudukLakilaki2024,proyeksiPendudukPerempuan2024,proyeksiPendudukJumlah2024,proyeksiPendudukPersentase2024,proyeksiPendudukKepadatan2024,proyeksiPendudukSexRatio2024,jumlahSekdes
0,6.105010e+09,NaN,6105010.0,1.102002e+06,61050.25005,Toba,Desa,Bagan Asam,644151982,1154270000,...,Tidak ada angkutan umum,Tanah,Sepanjang tahun kecuali saat tertentu,1541.0,1224.0,"2,765",15.92,9.32,126.0,1.0
1,6.105010e+09,NaN,6105010.0,1.102002e+06,61050.25005,Toba,Desa,Teraju,621419463,1120487000,...,"Ada, tanpa trayek tetap",Aspal/beton,Sepanjang tahun kecuali saat tertentu,2122.0,1987.0,"4,109",23.66,19.38,107.0,1.0
2,6.105010e+09,NaN,6105010.0,1.102002e+06,61050.25005,Toba,Desa,Kampung Baru,538018251,893987000,...,Tidak ada angkutan umum,Tanah,Selama musim kemarau,956.0,856.0,"1,812",10.43,13.35,112.0,1.0
3,6.105010e+09,NaN,6105010.0,1.102002e+06,61050.25005,Toba,Desa,Lumut,536414000,809502000,...,"Ada, dengan trayek tetap",Aspal/beton,Sepanjang tahun kecuali saat tertentu,1580.0,1453.0,"3,033",17.47,24.59,109.0,1.0
4,6.105010e+09,NaN,6105010.0,1.102002e+06,61050.25005,Toba,Desa,Sansat,618626755,1097760000,...,Tidak ada angkutan umum,"Diperkeras (kerikil, batu, dll.)",Sepanjang tahun kecuali saat tertentu,1011.0,881.0,"1,892",10.90,11.01,115.0,1.0

In [8]:
data_kcda2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 98 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   kodeDesa                                      258 non-null    float64
 1   volume                                        89 non-null     float64
 2   kodeKecamatan                                 258 non-null    float64
 3   katalog                                       258 non-null    float64
 4   noPublikasi                                   169 non-null    float64
 5   namaKecamatan                                 258 non-null    object
 6   statusDesKel                                  258 non-null    object
 7   namaDesa                                      258 non-null    object
 8   alokasiDanaDesa                               258 non-null    object
 9   danaDesa                                      258 non-null    object
 10  nikah                                         258 non-null    object
 11  rujuk                                         169 non-null    float64
 12  jumlahTalak                                   169 non-null    float64
 13  jumlahCerai                                   169 non-null    float64
 14  namaBabinsa                                   169 non-null    object
 15  namaBhabinkamtibnas                           169 non-null    object
 16  Tahun Publikasi                               169 non-null    float64
 17  Tahun Data                                    169 non-null    float64
 18  namaKecamatanBesar                            169 non-null    object
 19  NamaKelDesBesar                               169 non-null    object
 20  kec_keldes                                    169 non-null    object
 21  lahirLakiLaki                                 169 non-null    float64
 22  lahirPerempuan                                169 non-null    float64
 23  lahir                                         169 non-null    float64
 24  meninggalLakiLaki                             169 non-null    float64
 25  meninggalPerempuan                            169 non-null    float64
 26  meninggal                                     169 non-null    float64
 27  datangLakiLaki                                169 non-null    float64
 28  datangPerempuan                               169 non-null    float64
 29  datang                                        169 non-null    float64
 30  pindahLakiLaki                                169 non-null    float64
 31  pindahPerempuan                               169 non-null    float64
 32  pindah                                        169 non-null    float64
 33  wni                                           169 non-null    float64
 34  wna                                           169 non-null    float64
 35  Jumlah Penduduk Laki-Laki (sumber: Dukcapil)  169 non-null    float64
 36  Jumlah Penduduk Perempuan (sumber: Dukcapil)  169 non-null    float64
 37  Jumlah Penduduk Total (sumber: Dukcapil)      169 non-null    float64
 38  wajibKtp                                      169 non-null    float64
 39  memilikiKtp                                   169 non-null    float64
 40  belumMemilikiKtp                              169 non-null    float64
 41  wajibKK                                       169 non-null    float64
 42  memilikiKK                                    169 non-null    float64
 43  belumMemilikiKK                               169 non-null    float64
 44  islam                                         169 non-null    float64
 45  katolik                                       169 non-null    float64
 46  kristen                                       169 non-null    float64
 47  hindu                                         169 non-null    float64
 48  buddha                                        169 non-null    float64
 49  khonghucu                                     169 non-null    float64
 50  agamaLainnya                                  169 non-null    float64
 51  pembuatPublikasi                              169 non-null    object
 52  pemeriksaPublikasi                            169 non-null    object
 53  luasWilayahDesa                               169 non-null    float64
 54  persentaseLuasWilayahDesa                     169 non-null    float64
 55  jarakKecamatan                                169 non-null    float64
 56  jarakKantorBupati                             169 non-null    float64
 57  topografiDesa                                 169 non-null    object
 58  klasifikasiPerkotaanPerdesaan                 169 non-null    object
 59  TK                                            169 non-null    float64
 60  RA                                            169 non-null    float64
 61  SD                                            169 non-null    float64
 62  MI                                            169 non-null    float64
 63  SMP                                           169 non-null    float64
 64  MTS                                           169 non-null    float64
 65  SMA                                           169 non-null    float64
 66  MA                                            169 non-null    float64
 67  SMK                                           169 non-null    float64
 68  Akademi                                       169 non-null    float64
 69  masjid                                        169 non-null    float64
 70  mushola                                       169 non-null    float64
 71  gerejaProtestan                               169 non-null    float64
 72  gerejaKatholik                                169 non-null    float64
 73  kapel                                         169 non-null    float64
 74  pura                                          169 non-null    float64
 75  wihara                                        169 non-null    float64
 76  kelenteng                                     169 non-null    float64
 77  balaiBasarah                                  169 non-null    float64
 78  peribadatanLainnya                            169 non-null    float64
 79  jumlahPeribadatan                             169 non-null    float64
 80  r1005c                                        169 non-null    object
 81  r1005d                                        169 non-null    object
 82  keberadaanKantorPos                           169 non-null    object
 83  keberadaanPosKeliling                         169 non-null    object
 84  keberadaanJasaEkspedisi                       169 non-null    object
 85  namaKades                                     163 non-null    object
 86  jabatanKades                                  163 non-null    object
 87  r1001aString                                  169 non-null    object
 88  r1001c1String                                 169 non-null    object
 89  r1001b1String                                 169 non-null    object
 90  r403c2String                                  169 non-null    object
 91  proyeksiPendudukLakilaki2024                  169 non-null    float64
 92  proyeksiPendudukPerempuan2024                 169 non-null    float64
 93  proyeksiPendudukJumlah2024                    169 non-null    object
 94  proyeksiPendudukPersentase2024                169 non-null    float64
 95  proyeksiPendudukKepadatan2024                 169 non-null    float64
 96  proyeksiPendudukSexRatio2024                  169 non-null    float64
 97  jumlahSekdes                                  163 non-null    float64
dtypes: float64(71), object(27)
memory usage: 200.0+ KB

In [9]:
# grouping desa per kecamatan
grouped = data_kcda2026.groupby("namaKecamatan")

In [10]:
with open("template_new.jsx", "r", encoding="utf-8") as f:
    template = f.read()

In [11]:
output_folder = "generate_jsx"
os.makedirs(output_folder, exist_ok=True)

In [12]:
for nama_kecamatan, group in grouped:

    script = template  # copy template
    first = group.iloc[0]

    metadata = build_metadata(nama_kecamatan, first)

    for key, value in metadata.items():
        script = script.replace(f"{{{key}}}", str(value))

    script = inject_tables(script, group)

    filename = f"{nama_kecamatan}.jsx"
    filepath = os.path.join(output_folder, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(script)

print("✅ Semua Script Kecamatan berhasil dibuat!")

✅ Semua Script Kecamatan berhasil dibuat!